# macos specific dependencies

FIND_LIBRARY(FOUNDATION_LIBRARY Foundation)
FIND_LIBRARY(AV_FOUNDATION_LIBRARY AVFoundation)
FIND_LIBRARY(CORE_MEDIA_LIBRARY CoreMedia)

list(APPEND EXTERNAL_LIBRARIES
    ${FOUNDATION_LIBRARY}
    ${AV_FOUNDATION_LIBRARY}
    ${CORE_MEDIA_LIBRARY}
)
